# Generated by Django 5.0.4 on 2024-11-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employee_Management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
