# Generated by Django 5.1.2 on 2024-11-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employee_Management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.PositiveBigIntegerField(max_length=3),
        ),
    ]
