# Generated by Django 5.1.2 on 2024-11-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employee_Management", "0002_alter_employee_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_HR",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_emp",
            field=models.BooleanField(default=False),
        ),
    ]
