# Generated by Django 4.2.16 on 2024-11-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0004_alter_employee_id'),
        ('Employee_Management', '0004_logindetails'),
    ]

    operations = [
    ]
