# Generated by Django 5.0.4 on 2024-11-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employee_Management", "0005_merge_0004_alter_employee_id_0004_logindetails"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LoginDetails",
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.PositiveBigIntegerField(max_length=12),
        ),
    ]
