# Generated by Django 5.0.4 on 2024-11-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employee_Management", "0009_logindetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="password",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
