# Generated by Django 5.0.4 on 2024-12-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employee_Management", "0011_employee_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="logindetails",
            name="otp_expiration_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
