# Generated by Django 5.0.4 on 2024-12-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employee_Management", "0012_logindetails_otp_expiration_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logindetails",
            name="employee_id",
            field=models.CharField(max_length=20),
        ),
    ]
