# Generated by Django 4.2.16 on 2024-11-05 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClockInOut',
            fields=[
                ('E_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('login_attempts', models.PositiveIntegerField(default=0)),
                ('reset_attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
