# Generated by Django 5.0.4 on 2024-11-27 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClockInOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("E_id", models.CharField(max_length=12)),
                ("login_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("shift_end_time", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("login_attempts", models.PositiveIntegerField(default=0)),
                ("reset_attempts", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyTarget",
            fields=[
                ("target_id", models.AutoField(primary_key=True, serialize=False)),
                ("month", models.CharField(max_length=20)),
                ("year", models.IntegerField()),
                ("target_value", models.FloatField()),
                ("actual_value", models.FloatField()),
                ("difference", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(max_length=20)),
                ("emp_id", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
