# Generated by Django 5.1 on 2024-11-06 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockinout',
            name='logout_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
