# Generated by Django 4.2.16 on 2024-11-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_clockinout_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockinout',
            name='working_hours',
            field=models.IntegerField(default=8),
        ),
    ]
