# Generated by Django 5.1 on 2024-11-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_clockinout_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockinout',
            name='shift_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
