# Generated by Django 4.2.16 on 2024-11-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_clockinout_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockinout',
            name='reminder_3_min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clockinout',
            name='reminder_5_min',
            field=models.BooleanField(default=False),
        ),
    ]
