# Generated by Django 5.1 on 2024-11-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_clockinout_shift_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockinout',
            name='shift_end_time',
        ),
    ]
