# Generated by Django 5.1 on 2024-11-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_clockinout_shift_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockinout',
            name='shift_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
