# Generated by Django 4.2.16 on 2024-11-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_reminder_3_min_clockinout_reminder_3_min_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clockinout',
            name='reminder_3_min_sent',
        ),
    ]
