# Generated by Django 5.1 on 2024-11-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_clockinout_shift_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('target_value', models.FloatField()),
                ('actual_value', models.FloatField()),
                ('difference', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('emp_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
