# Generated by Django 4.2.16 on 2024-11-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_monthlytarget'),
        ('dashboard', '0007_remove_clockinout_reminder_3_min_sent'),
    ]

    operations = [
    ]
