# Generated by Django 5.0.4 on 2024-12-11 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("E_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="designation.designation",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Floor_Manager",
        ),
        migrations.DeleteModel(
            name="Vertical_Manager",
        ),
    ]
