# Generated by Django 5.0.4 on 2024-12-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("designation", "0002_designation_delete_floor_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designation",
            name="reports_to",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
