# Generated by Django 5.0.4 on 2024-11-16 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Calender", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="holiday",
            name="date",
        ),
        migrations.RemoveField(
            model_name="holiday",
            name="name",
        ),
    ]
