# Generated by Django 5.0.4 on 2024-11-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Calender", "0003_holiday_date_holiday_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
